name: CI
on: [push]

# See: https://dev.to/shofol/run-your-github-actions-jobs-from-a-specific-directory-1i9e
defaults:
  run:
    working-directory: web

jobs:
  lint:
    name: Lint, format and check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Validate files
        run: npm run validate
